### ISSUE TITLE
玩家重进世界后蒸汽机内水不渲染

### ISSUE THREAD

**Issue by vvvbbbcz** [BinZhengStudio/IndustryBase#24]

**Comment by foreverStarship** [comment]
问题具体描述：
当玩家重进世界时，发现未工作的蒸汽机中的水消失（前提是里面已经有水了），未渲染。
在加入水或者令蒸汽机开始工作后水重新出现。

问题原因的猜测：
client/renderer/blockentity/SteamEngineRenderer.java 第 42 行到第 61 行代码块仅在客户端执行。
world/level/block/entity/SteamEngineBlockEntity.java 第 173 行到第 175 行代码块同理。
而服务器端仅在蒸汽机工作时发包（world/level/block/entity/SteamEngineBlockEntity.java 第 85 行到第 142 行代码块），且退出重进会使同步数据清除。
综上问题导致客户端无法正常渲染未工作的蒸汽机。


问题的复现方法：
放置一个蒸汽机（不要加入燃料），灌满水，退出重进，水消失。
