### ISSUE TITLE
/fill 指令填充大量导线的卡顿问题

### ISSUE THREAD

**Issue by foreverStarship** [BinZhengStudio/IndustryBase#32]
问题具体描述：
使用 /fill 指令一次性放置大量导线方块或者接线端子时会出现较为严重的卡顿或延迟（测试 fill 的方块数量约 11000 个）。

问题原因的猜测：
在 fill 指令一次性填充大量导线的情况下，能量网络通断检测等算法计算量过大，导致响应缓慢。
不过这很大可能只是优化问题，所以解决的办法是优化算法。

问题的复现方法：
进入游戏，使用 /fill 指令一次性填充大量导线方块。

其他详细信息：
Java 版本：Oracle OpenJDK version 17.0.6
Mod 版本：industrybase-1.20.1-0.3.0-alpha.1
CPU：AMD Ryzen 5 5500
GPU：AMD Radeon RX 580 Series
内存分配：512 MB ~ 4096 MB

**Comment by vvvbbbcz** [comment]
经过测试，这个问题与算法无关。

算法逻辑是这样的，新增方块动作发生后，**并不会立即更新能量网络**，而是在下一个 tick 的开头处更新，所以卡顿与算法无关。如果是在方块成功放置后，才出现生物不动、右键方块无反应等情况（即服务端卡顿而客户端正常），才可以认定为算法问题。

之所以不会立即更新能量网络，是因为它需要检测周围方块状态，而很多时候导线是在世界加载阶段添加的，此时检测周围方块状态容易锁死。
